name: ghpage
on: push

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip doc')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -U pip
          pip install Sphinx sphinx-rtd-theme
          pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install -U .

      - name: build
        run: |
          . venv/bin/activate
          cd docs
          make clean
          make html

      - name: push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
#         To avoid throwing exit1 if there is no file to commit
#         https://stackoverflow.com/questions/47036884/how-to-git-commit-with-persistent-exit-0-status
          git diff-index --quiet HEAD || git commit -am 'update doc'
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF}
